[package]
name = "colorpattern"
version = "0.1.0"
authors = ["Mark Heijnekamp <mark@heijnekamp.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rgb = "0.8"
num = "0.1.27"
image = "0.13.0"
